enum {
	TAP_FUSE_CHECK,
	TAP_TEST_LOGIC_RESET,
	TAP_RUN_TEST_IDLE,
	TAP_SELECT_DR_SCAN,
	TAP_CAPTURE_DR,
	TAP_SHIFT_DR,
	TAP_EXIT1_DR,
	TAP_PAUSE_DR,
	TAP_EXIT2_DR,
	TAP_UPDATE_DR,
	TAP_SELECT_IR_SCAN,
	TAP_CAPTURE_IR,
	TAP_SHIFT_IR,
	TAP_EXIT1_IR,

};
