#ifndef STATUS_H_
#define STATUS_H_

/* Not finalized yet */

#define STATUS_OK                200
#define STATUS_CONTENT_MISMATCH  201
#define STATUS_CONTINUE_TRANSFER 350
#define STATUS_TIMED_OUT         400
#define STATUS_TRANSFER_FAILED   401
#define STATUS_UNKNOWN_COMMAND   500
#define STATUS_INVALID_ARGUMENTS 501
#define STATUS_INTEGER_OVERFLOW  502
#define STATUS_COMMAND_TOO_LONG  503
#define STATUS_FUSE_BLOWN        550
#define STATUS_INVALID_JTAG_ID   551
#define STATUS_PUC_FAILED        552
#define STATUS_TOO_MANY_BREAKS   553
#define STATUS_OUT_OF_BOUNDS     554

#endif
